### ISSUE TITLE
Please support Cr 6.5

### ISSUE THREAD

**Issue by kKuteKuto** [306bobby-android/crDroid-build-signed-script#2]
My device run crDroid 6.5 A10
Please update code to support 
Thanks

**Comment by DrFunkenbreakz** [comment]
I doubt crdoid 6.5 source code exits and is still buildable from source as it was dropped from support some time ago. Assuming the changes you want could be made (I don't know), you would still need to build that old crdroid version from source to produce a signed rom zip.

Being realistic, I dont think your request will be done. Im just replying so you understand its not just a case of runnning a script to sign an already built rom zip.

**Comment by ask9027** [comment]
is it possible to sign full rom.zip if custom rom not signed while build?

**Comment by DrFunkenbreakz** [comment]
> is it possible to sign full rom.zip if custom rom not signed while build?

No
