### ISSUE TITLE
Redroid compatibility

### ISSUE THREAD

**Issue by FreedomLabsIO** [306bobby-android/crDroid-build-signed-script#7]
Hi @306bobby-android ! Can you make the script compatible with [Redroid](https://github.com/remote-android/redroid-doc) ?

I tried it but it in the generated build, the prop files have the tags `dev-keys` instead of `release-keys`.
And the image doesn't work, device is always `offline`

```
ubuntu@ubuntu:~/redroid/out/target/product/redroid_arm64_only$ sudo grep -r ".tags=" . --include="*.prop"
./ramdisk/system/etc/ramdisk/build.prop:ro.bootimage.build.tags=dev-keys
./system/system_ext/etc/build.prop:ro.system_ext.build.tags=dev-keys
./system/product/etc/build.prop:ro.product.build.tags=dev-keys
./system/build.prop:ro.system.build.tags=dev-keys
./system/build.prop:ro.build.tags=dev-keys
./obj/PACKAGING/target_files_intermediates/redroid_arm64_only-target_files-eng.ubuntu/SYSTEM/system_ext/etc/build.prop:ro.system_ext.build.tags=dev-keys
./obj/PACKAGING/target_files_intermediates/redroid_arm64_only-target_files-eng.ubuntu/SYSTEM/product/etc/build.prop:ro.product.build.tags=dev-keys
./obj/PACKAGING/target_files_intermediates/redroid_arm64_only-target_files-eng.ubuntu/SYSTEM/build.prop:ro.system.build.tags=dev-keys
./obj/PACKAGING/target_files_intermediates/redroid_arm64_only-target_files-eng.ubuntu/SYSTEM/build.prop:ro.build.tags=dev-keys
./obj/PACKAGING/target_files_intermediates/redroid_arm64_only-target_files-eng.ubuntu/VENDOR/vendor_dlkm/etc/build.prop:ro.vendor_dlkm.build.tags=dev-keys
./obj/PACKAGING/target_files_intermediates/redroid_arm64_only-target_files-eng.ubuntu/VENDOR/build.prop:ro.vendor.build.tags=dev-keys
./obj/PACKAGING/target_files_intermediates/redroid_arm64_only-target_files-eng.ubuntu/VENDOR/odm_dlkm/etc/build.prop:ro.odm_dlkm.build.tags=dev-keys
./obj/PACKAGING/target_files_intermediates/redroid_arm64_only-target_files-eng.ubuntu/VENDOR/odm/etc/build.prop:ro.odm.build.tags=dev-keys
./obj/PACKAGING/target_files_intermediates/redroid_arm64_only-target_files-eng.ubuntu/BOOT/RAMDISK/system/etc/ramdisk/build.prop:ro.bootimage.build.tags=dev-keys
./obj/PACKAGING/system_build_prop_intermediates/buildinfo.prop:ro.build.tags=dev-keys
./vendor/vendor_dlkm/etc/build.prop:ro.vendor_dlkm.build.tags=dev-keys
./vendor/build.prop:ro.vendor.build.tags=dev-keys
./vendor/odm_dlkm/etc/build.prop:ro.odm_dlkm.build.tags=dev-keys
./vendor/odm/etc/build.prop:ro.odm.build.tags=dev-keys 
```

**Comment by 306bobby-android** [comment]
Did your PR fix the issue?

Optional include was how it was written in LOS documentation and works for most LOS based ROMs, but if not making optional works fine and enables support elsewhere, that's fine. 

Just need to make sure it doesn't break lineage-based

**Comment by FreedomLabsIO** [comment]
> Did your PR fix the issue?
> 
> Optional include was how it was written in LOS documentation and works for most LOS based ROMs, but if not making optional works fine and enables support elsewhere, that's fine.
> 
> Just need to make sure it doesn't break lineage-based

No, my PR is not related to this incompatibility with Redroid.

The PR is because of a simple check.
What's the point of adding `-include vendor/lineage-priv/keys/keys.mk` to the device tree if the file `vendor/lineage-priv/keys/keys.mk` could possibly not exist? If there's a `-` (optional) flag, when I forget to create the keys.mk file it will not throw an error, while it should, to remind the user to create the `keys.mk` file (execute the script).

Something similar happened to me earlier, i create `keys.mk` file but in the wrong folder (I was doing the process manually). And because the `-` flag was there, it didn't throw any errors. So I wasted a couple of minutes till I figured it out.

**Comment by 306bobby-android** [comment]
> The PR is because of a simple check. What's the point of adding `-include vendor/lineage-priv/keys/keys.mk` to the device tree if the file `vendor/lineage-priv/keys/keys.mk` could possibly not exist? If there's a `-` (optional) flag, when I forget to create the keys.mk file it will not throw an error, while it should, to remind the user to create the `keys.mk` file (execute the script).

The script creates the make file
```
## Create vendor for keys
mkdir -p vendor/lineage-priv
mv ~/.android-certs vendor/lineage-priv/keys
echo "PRODUCT_DEFAULT_DEV_CERTIFICATE := vendor/lineage-priv/keys/releasekey" > vendor/lineage-priv/keys/keys.mk
cat <<EOF > vendor/lineage-priv/keys/BUILD.bazel
filegroup(
    name = "android_certificate_directory",
    srcs = glob([
        "*.pk8",
        "*.pem",
    ]),
    visibility = ["//visibility:public"],
)
EOF
```
Something wildly incorrect happened if the make file somehow wasn't there

The point of the optional is if a ROM maintainer pushed it to their DT, that way normal builders aren't forced to create their own keys without first looking through the process

**Comment by FreedomLabsIO** [comment]
> > The PR is because of a simple check. What's the point of adding `-include vendor/lineage-priv/keys/keys.mk` to the device tree if the file `vendor/lineage-priv/keys/keys.mk` could possibly not exist? If there's a `-` (optional) flag, when I forget to create the keys.mk file it will not throw an error, while it should, to remind the user to create the `keys.mk` file (execute the script).
> 
> The script creates the make file
> 
> ```
> ## Create vendor for keys
> mkdir -p vendor/lineage-priv
> mv ~/.android-certs vendor/lineage-priv/keys
> echo "PRODUCT_DEFAULT_DEV_CERTIFICATE := vendor/lineage-priv/keys/releasekey" > vendor/lineage-priv/keys/keys.mk
> cat <<EOF > vendor/lineage-priv/keys/BUILD.bazel
> filegroup(
>     name = "android_certificate_directory",
>     srcs = glob([
>         "*.pk8",
>         "*.pem",
>     ]),
>     visibility = ["//visibility:public"],
> )
> EOF
> ```
> 
> Something wildly incorrect happened if the make file somehow wasn't there

Yeah I know... my PR is just a dumb check... because I was dumb earlier.
Ok, it makes sense, I got your point. I'll close the PR.

**Comment by 306bobby-android** [comment]
> > > The PR is because of a simple check. What's the point of adding `-include vendor/lineage-priv/keys/keys.mk` to the device tree if the file `vendor/lineage-priv/keys/keys.mk` could possibly not exist? If there's a `-` (optional) flag, when I forget to create the keys.mk file it will not throw an error, while it should, to remind the user to create the `keys.mk` file (execute the script).
> > 
> > 
> > The script creates the make file
> > ```
> > ## Create vendor for keys
> > mkdir -p vendor/lineage-priv
> > mv ~/.android-certs vendor/lineage-priv/keys
> > echo "PRODUCT_DEFAULT_DEV_CERTIFICATE := vendor/lineage-priv/keys/releasekey" > vendor/lineage-priv/keys/keys.mk
> > cat <<EOF > vendor/lineage-priv/keys/BUILD.bazel
> > filegroup(
> >     name = "android_certificate_directory",
> >     srcs = glob([
> >         "*.pk8",
> >         "*.pem",
> >     ]),
> >     visibility = ["//visibility:public"],
> > )
> > EOF
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Something wildly incorrect happened if the make file somehow wasn't there
> 
> Yeah I know... my PR is just a dumb check... because I was dumb earlier. Ok, it makes sense, I got your point. I'll close the PR.

Do check my edit, as I understand your point, too. I just did have my own reasons as well

**Comment by 306bobby-android** [comment]
Let me look into redroid. Is it aosp or lineage based. If aosp, that may be the issue

**Comment by FreedomLabsIO** [comment]
> Let me look into redroid. Is it aosp or lineage based. If aosp, that may be the issue

AOSP
