### ISSUE TITLE
I don't have enough knowledge to use this

### ISSUE THREAD

**Issue by mso45mso** [306bobby-android/crDroid-build-signed-script#8]
Hello, I am quite new to these issues. I need a signed rom to pass play integrity, but I don't understand how to sign my rom. Is there a short tutorial video or a more detailed article for this?

I am using windows.

**Comment by 306bobby-android** [comment]
You don't "sign a ROM', you build the ROM using these keys instead of supplied test keys. Learn about building ROMs first.
